specVersion: 0.0.1
description: ""
repository: "https://github.com/darwinia-network/subql"
schema: ./schema.graphql
network:
  endpoint: wss://kusama.api.onfinality.io/public-ws
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 8494000
    mapping:
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
        - handler: handleCall
          kind: substrate/CallHandler
