specVersion: 0.0.1
description: ""
repository: ""
schema: ./schema.graphql
network:
  endpoint: wss://pangolin-rpc.darwinia.network/
  types:
    UsableBalance:
      usableBalance: Balance
    Status:
      _enum:
        Free: "Null"
        Reserved: "Null"
    Address: MultiAddress
    LookupSource: MultiAddress
    MultiAddress: GenericMultiAddress
    BalanceInfo: "{}"
    BalanceLock:
      id: LockIdentifier
      lockFor: LockFor
      reasons: Reasons
    LockFor:
      _enum:
        Common: Common
        Staking: StakingLock
    Common:
      amount: Balance
    StakingLock:
      stakingAmount: Balance
      unbondings: Vec<Unbonding>
    Reasons:
      _enum:
        - Fee
        - Misc
        - All
    Unbonding:
      amount: Balance
      moment: BlockNumber
    AccountData:
      free: Balance
      reserved: Balance
      freeKton: Balance
      reservedKton: Balance
      miscFrozen: Balance
      feeFrozen: Balance
    RingBalance: Balance
    KtonBalance: Balance
    TsInMs: u64
    Power: u32
    DepositId: U256
    StakingBalanceT:
      _enum:
        RingBalance: Balance
        KtonBalance: Balance
    StakingLedgerT:
      stash: AccountId
      activeRing: Compact<Balance>
      activeDepositRing: Compact<Balance>
      activeKton: Compact<Balance>
      depositItems: Vec<TimeDepositItem>
      ringStakingLock: StakingLock
      ktonStakingLock: StakingLock
      claimedRewards: Vec<EraIndex>
    TimeDepositItem:
      value: Compact<Balance>
      startTime: Compact<TsInMs>
      expireTime: Compact<TsInMs>
    ExposureT:
      ownRingBalance: Compact<Balance>
      ownKtonBalance: Compact<Balance>
      ownPower: Power
      totalPower: Power
      others: Vec<IndividualExposure>
    Exposure: ExposureT
    IndividualExposure:
      who: AccountId
      ringBalance: Compact<Balance>
      ktonBalance: Compact<Balance>
      power: Power
    ElectionResultT:
      electedStashes: Vec<AccountId>
      exposures: Vec<(AccountId, ExposureT)>
      compute: ElectionCompute
    RKT:
      r: Balance
      k: Balance
    SpanRecord:
      slashed: RKT
      paidOut: RKT
    UnappliedSlash:
      validator: AccountId
      own: RKT
      others: Vec<(AccountId, RKT)>
      reporters: Vec<AccountId>
      payout: RKT
    TreasuryProposal:
      proposer: AccountId
      beneficiary: AccountId
      ringValue: Balance
      ktonValue: Balance
      ringBond: Balance
      ktonBond: Balance
    MappedRing: u128
    EthereumTransactionIndex: "(H256, u64)"
    EthereumBlockNumber: u64
    EthereumHeader:
      parentHash: H256
      timestamp: u64
      number: EthereumBlockNumber
      author: EthereumAddress
      transactionsRoot: H256
      unclesHash: H256
      extraData: Bytes
      stateRoot: H256
      receiptsRoot: H256
      logBloom: Bloom
      gasUsed: U256
      gasLimit: U256
      difficulty: U256
      seal: Vec<Bytes>
      blockHash: Option<H256>
    EthereumAddress: H160
    Bloom: "[u8; 256; Bloom]"
    H128: "[u8; 16; H128]"
    EthashProof:
      dagNodes: "(H512, H512)"
      proof: Vec<H128>
    EthereumReceipt:
      gasUsed: U256
      logBloom: Bloom
      logs: Vec<LogEntry>
      outcome: TransactionOutcome
    LogEntry: "{}"
    TransactionOutcome: "{}"
    EthereumNetworkType:
      _enum:
        Mainnet: "Null"
        Ropsten: "Null"
    RedeemFor:
      _enum:
        Token: "Null"
        Deposit: "Null"
    EthereumReceiptProof:
      index: u64
      proof: Bytes
      headerHash: H256
    EthereumReceiptProofThing: "(EthereumHeader, EthereumReceiptProof, MMRProof)"
    MMRProof:
      memberLeafIndex: u64
      lastLeafIndex: u64
      proof: Vec<H256>
    EthereumRelayHeaderParcel:
      header: EthereumHeader
      parentMmrRoot: H256
    EthereumRelayProofs:
      ethashProof: Vec<EthashProof>
      mmrProof: Vec<H256>
    OtherSignature:
      _enum:
        Eth: EcdsaSignature
        Tron: EcdsaSignature
    EcdsaSignature: "[u8; 65; EcdsaSignature]"
    TronAddress: EthereumAddress
    OtherAddress:
      _enum:
        Eth: EthereumAddress
        Tron: TronAddress
    AddressT: "[u8; 20; AddressT]"
    MerkleMountainRangeRootLog:
      prefix: "[u8; 4; Prefix]"
      ParentMmrRoot: Hash
    ChainProperties:
      ss58Format: Option<u8>
      tokenDecimals: Option<Vec<u32>>
      tokenSymbol: Option<Vec<Text>>
    AccountInfo: AccountInfoWithTripleRefCount
    AccountInfoWithTripleRefCount:
      nonce: Index
      consumers: RefCount
      providers: RefCount
      sufficients: RefCount
      data: AccountData
    Signer: EthereumAddress
    RelayAuthorityT:
      accountId: AccountId
      signer: Signer
      stake: Balance
      term: BlockNumber
    MMRRoot: Hash
    EcdsaAddress: EthereumAddress
    EcdsaMessage: H256
    RelayAuthoritySigner: EcdsaAddress
    RelayAuthorityMessage: EcdsaMessage
    RelayAuthoritySignature: EcdsaSignature
    Term: BlockNumber
    OpCode: "[u8; 4; OpCode]"
    ScheduledAuthoritiesChangeT:
      nextAuthorities: Vec<RelayAuthorityT>
      deadline: BlockNumber
    ElectionCompute:
      _enum:
        - OnChain
        - Signed
        - Authority
    MMRProofResult:
      mmrSize: u64
      proof: Text
    ProxyDefinition:
      delegate: AccountId
      proxyType: ProxyType
      delay: BlockNumber
    ProxyType:
      _enum:
        Any: "Null"
        NonTransfer: "Null"
        Governance: "Null"
        Staking: "Null"
        IdentityJudgement: "Null"
        EthereumBridge: "Null"
    ProxyAnnouncement:
      real: AccountId
      callHash: Hash
      height: BlockNumber
    Announcement: ProxyAnnouncement
    RelayHeaderId: EthereumBlockNumber
    RelayHeaderParcel: EthereumRelayHeaderParcel
    RelayProofs: EthereumRelayProofs
    RelayAffirmationId:
      relayHeaderId: EthereumBlockNumber
      round: u32
      index: u32
    RelayAffirmationT:
      relayer: AccountId
      relayHeaderParcels: EthereumRelayHeaderParcel
      bond: Balance
      maybeExtendedRelayAffirmationId: Option<RelayAffirmationId>
      verified: bool
    RelayVotingState:
      ayes: Vec<AccountId>
      nays: Vec<AccountId>
    PowerOf:
      power: Power
    BabeEpochConfiguration: "Null"
    ValidatorPrefs: ValidatorPrefsWithBlocked
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 30700
    mapping:
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Deposit
        - handler: handleCall
          kind: substrate/CallHandler
