specVersion: 0.0.1
description: ""
repository: "https://github.com/darwinia-network/subql"
schema: ./schema.graphql
network:
  endpoint: wss://kusama.elara.patract.io
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 8494000
    mapping:
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Deposit
        - handler: handleCall
          kind: substrate/CallHandler
